# SwiftLint configuration for CouchVision
# See: https://realm.github.io/SwiftLint/rule-directory.html
# Aligned with .swiftformat settings

excluded:
  - .build
  - DerivedData
  - build
  - .swiftpm

disabled_rules:
  - todo  # TODOs are fine during development
  - trailing_comma  # Allow trailing commas (SwiftFormat handles this)

opt_in_rules:
  # Performance
  - empty_count
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - flatmap_over_map_reduce
  - last_where
  - reduce_into

  # Safety
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_super_call
  - fatal_error_message
  - discouraged_optional_boolean

  # Clarity
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - redundant_type_annotation
  - toggle_bool
  - joined_default_parameter
  - empty_string
  - empty_collection_literal

  # Modern Swift
  - prefer_zero_over_explicit_init
  - shorthand_optional_binding

# Allow short names for math/coordinates (x, y, z, etc.)
identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - w
    - u
    - v
    - i
    - j
    - k
    - fx
    - fy
    - cx
    - cy

# Tuples for point data are acceptable
large_tuple:
  warning: 5
  error: 6

# Match SwiftFormat's maxwidth setting
line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 400
  error: 500

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level: 2
  function_level: 3

# Force cast is sometimes necessary for iOS APIs
force_cast:
  severity: warning

# Allow implicit returns in closures and computed properties
implicit_return:
  included:
    - closure
    - getter

# Reporter for CI integration
reporter: xcode
