name: CouchVision
options:
  bundleIdPrefix: com.couchvision
  deploymentTarget:
    iOS: "16.2"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1" # iPhone only
    INFOPLIST_FILE: CouchVision/Resources/Info.plist
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
  configs:
    Release:
      CODE_SIGN_STYLE: Manual
      DEVELOPMENT_TEAM: 9778KTLRXB

targets:
  CouchVision:
    type: application
    platform: iOS
    sources:
      - CouchVision
      - path: CouchVisionWidgets/StreamingActivityAttributes.swift
        group: CouchVisionWidgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.couchvision.CouchVision
        INFOPLIST_FILE: CouchVision/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
      configs:
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "CouchVision GitHub Action Distribution"
    info:
      path: CouchVision/Resources/Info.plist
      properties:
        CFBundleDisplayName: CouchVision
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "2"
        CFBundleIconName: AppIcon
        ITSAppUsesNonExemptEncryption: false
        NSSupportsLiveActivities: true
        NSSupportsLiveActivitiesFrequentUpdates: true
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiresFullScreen: true
        UIRequiredDeviceCapabilities:
          - armv7
        # Permissions
        NSCameraUsageDescription: "CouchVision streams camera data to ROS2 for robotics applications."
        NSLocationWhenInUseUsageDescription: "CouchVision streams GPS location to ROS2 for robotics applications."
        NSLocationAlwaysAndWhenInUseUsageDescription: "CouchVision needs location access in background to maintain connection and stream GPS data."
        NSMotionUsageDescription: "CouchVision streams IMU sensor data to ROS2 for robotics applications."
        # Background Modes
        UIBackgroundModes:
          - location
          - audio
    dependencies:
      - target: CouchVisionWidgets
        embed: true

  CouchVisionWidgets:
    type: app-extension
    platform: iOS
    sources:
      - CouchVisionWidgets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.couchvision.CouchVision.Widgets
        INFOPLIST_FILE: CouchVisionWidgets/Info.plist
        SKIP_INSTALL: YES
      configs:
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "CouchVision Widgets GitHub Action Distribution"
    info:
      path: CouchVisionWidgets/Info.plist
      properties:
        CFBundleDisplayName: CouchVision Widgets
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "2"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
